$SlashStarBlock = @{ Start = '^/\*'; End = '\*/' }
$MarkupBlock = @{ Start = '^<!--'; End = '-->' }
$RazorBlock = @{ Start = '^@\*'; End = '\*@' }
$PowerShellBlock = @{ Start = '^<#'; End = '#>' }

$CStyleComment = @{ LineStart = '^(//|/\*|\*)'; Trailing = '\s//\s'; Blocks = @($SlashStarBlock) }
$CssComment = @{ LineStart = '^(/\*|\*)'; Trailing = $null; Blocks = @($SlashStarBlock) }
$RazorComment = @{ LineStart = '^(@\*|//|/\*|<!--)'; Trailing = '\s//\s'; Blocks = @($RazorBlock, $SlashStarBlock, $MarkupBlock) }
$HashComment = @{ LineStart = '^(#|<#)'; Trailing = $null; Blocks = @($PowerShellBlock) }
$SqlComment = @{ LineStart = '^(--|/\*)'; Trailing = '\s--\s'; Blocks = @($SlashStarBlock) }
$MarkupComment = @{ LineStart = '^<!--'; Trailing = $null; Blocks = @($MarkupBlock) }

$CommentSyntaxByExtension = @{
    '.cs' = $CStyleComment; '.ts' = $CStyleComment; '.tsx' = $CStyleComment
    '.js' = $CStyleComment; '.jsx' = $CStyleComment; '.mjs' = $CStyleComment; '.cjs' = $CStyleComment
    '.java' = $CStyleComment; '.go' = $CStyleComment; '.kt' = $CStyleComment
    '.cpp' = $CStyleComment; '.h' = $CStyleComment; '.scss' = $CStyleComment; '.less' = $CStyleComment
    '.css' = $CssComment
    '.razor' = $RazorComment; '.cshtml' = $RazorComment
    '.ps1' = $HashComment; '.psm1' = $HashComment; '.psd1' = $HashComment; '.py' = $HashComment; '.sh' = $HashComment
    '.sql' = $SqlComment
    '.xml' = $MarkupComment; '.html' = $MarkupComment; '.xaml' = $MarkupComment; '.csproj' = $MarkupComment
    '.props' = $MarkupComment; '.targets' = $MarkupComment; '.config' = $MarkupComment; '.vue' = $MarkupComment
}

$NonCommentDirectives = @(
    '^#(region|endregion|requires)\b'
    '^#!'
    '^# -\*- coding'
    '^// <auto-generated'
    '^/// <reference'
    '^// eslint-'
    '^// @ts-'
    '^// prettier-ignore'
    '^// ReSharper '
    'SPDX-'
    'Copyright'
)

$MaxBlocksShown = 5
$MaxPreviewLength = 100

function Main {
    $hookInput = Read-HookInput
    $filePath = $hookInput.tool_input.file_path
    $syntax = Get-CommentSyntax -FilePath $filePath
    if (-not $syntax) {
        return
    }

    $addedLines = @(Get-AddedLines -HookInput $hookInput)
    $blocks = @(Select-CommentBlocks -AddedLines $addedLines -Syntax $syntax)
    if ($blocks.Count -eq 0) {
        return
    }

    $fileName = [IO.Path]::GetFileName($filePath)
    Write-HookContext -Text (Format-CommentReminder -FileName $fileName -Blocks $blocks)
}

function Read-HookInput {
    [Console]::InputEncoding = New-Object Text.UTF8Encoding $false
    return [Console]::In.ReadToEnd() | ConvertFrom-Json
}

function Write-HookContext {
    param([string] $Text)

    $output = @{
        hookSpecificOutput = @{
            hookEventName = 'PostToolUse'
            additionalContext = $Text
        }
    }
    [Console]::OutputEncoding = New-Object Text.UTF8Encoding $false
    [Console]::Out.Write(($output | ConvertTo-Json -Compress -Depth 3))
}

function Get-CommentSyntax {
    param([string] $FilePath)

    if (-not $FilePath) {
        return $null
    }
    return $CommentSyntaxByExtension[[IO.Path]::GetExtension($FilePath).ToLowerInvariant()]
}

function Get-AddedLines {
    param($HookInput)

    $patch = @($HookInput.tool_response.structuredPatch | Where-Object { $_ })
    if ($patch.Count -gt 0) {
        return Get-PatchAddedLines -Patch $patch
    }
    if ($null -ne $HookInput.tool_input.content) {
        return Get-WriteAddedLines -Content $HookInput.tool_input.content
    }
    return Get-EditAddedLines -ToolInput $HookInput.tool_input
}

function Get-PatchAddedLines {
    param($Patch)

    foreach ($hunk in $Patch) {
        $lineNumber = [int] $hunk.newStart
        foreach ($line in $hunk.lines) {
            if ($line.StartsWith('+')) {
                New-AddedLine -LineNumber $lineNumber -Text $line.Substring(1)
                $lineNumber++
            }
            elseif ($line.StartsWith(' ')) {
                $lineNumber++
            }
        }
    }
}

function Get-EditAddedLines {
    param($ToolInput)

    $edits = @($ToolInput.edits | Where-Object { $_ })
    if ($edits.Count -eq 0) {
        $edits = @($ToolInput)
    }

    foreach ($edit in $edits) {
        $keptLines = @{}
        foreach ($line in (Split-Lines $edit.old_string)) {
            $keptLines[$line.Trim()] = $true
        }
        foreach ($line in (Split-Lines $edit.new_string)) {
            if (-not $keptLines.ContainsKey($line.Trim())) {
                New-AddedLine -LineNumber $null -Text $line
            }
        }
    }
}

function Get-WriteAddedLines {
    param([string] $Content)

    $lineNumber = 1
    foreach ($line in (Split-Lines $Content)) {
        New-AddedLine -LineNumber $lineNumber -Text $line
        $lineNumber++
    }
}

function New-AddedLine {
    param($LineNumber, [string] $Text)

    return [pscustomobject] @{ LineNumber = $LineNumber; Text = $Text }
}

function Split-Lines {
    param([string] $Text)

    if (-not $Text) {
        return @()
    }
    return $Text -split '\r?\n'
}

function Select-CommentBlocks {
    param($AddedLines, $Syntax)

    $currentBlock = $null
    $previousLine = $null
    $openBlockEnd = $null
    foreach ($line in $AddedLines) {
        if ($openBlockEnd) {
            if ($line.Text -match $openBlockEnd) {
                $openBlockEnd = $null
            }
        }
        elseif (Test-IsComment -Text $line.Text -Syntax $Syntax) {
            $openBlockEnd = Get-UnclosedBlockEnd -Text $line.Text -Syntax $Syntax
        }
        else {
            $currentBlock = $null
            $previousLine = $line
            continue
        }

        if ($currentBlock -and (Test-IsNextLine -Previous $previousLine -Current $line)) {
            $currentBlock.LineCount++
        }
        else {
            $currentBlock = [pscustomobject] @{
                LineNumber = $line.LineNumber
                LineCount = 1
                FirstLine = $line.Text.Trim()
            }
            $currentBlock
        }
        $previousLine = $line
    }
}

function Get-UnclosedBlockEnd {
    param([string] $Text, $Syntax)

    $trimmed = $Text.Trim()
    foreach ($block in $Syntax.Blocks) {
        $start = [regex]::Match($trimmed, $block.Start)
        if (-not $start.Success) {
            continue
        }
        $afterStart = $trimmed.Substring($start.Length)
        if ($afterStart -match $block.End) {
            return $null
        }
        return $block.End
    }
    return $null
}

function Test-IsNextLine {
    param($Previous, $Current)

    if ($null -eq $Previous.LineNumber -or $null -eq $Current.LineNumber) {
        return $true
    }
    return $Current.LineNumber -eq $Previous.LineNumber + 1
}

function Test-IsComment {
    param([string] $Text, $Syntax)

    $trimmed = $Text.Trim()
    if (-not $trimmed) {
        return $false
    }
    foreach ($directive in $NonCommentDirectives) {
        if ($trimmed -match $directive) {
            return $false
        }
    }
    if ($trimmed -match $Syntax.LineStart) {
        return $true
    }
    return Test-HasTrailingComment -Text $trimmed -Pattern $Syntax.Trailing
}

function Test-HasTrailingComment {
    param([string] $Text, [string] $Pattern)

    if (-not $Pattern) {
        return $false
    }
    $match = [regex]::Match($Text, $Pattern)
    if (-not $match.Success) {
        return $false
    }
    $codeBefore = $Text.Substring(0, $match.Index)
    $doubleQuotes = ($codeBefore.ToCharArray() | Where-Object { $_ -eq '"' }).Count
    $singleQuotes = ($codeBefore.ToCharArray() | Where-Object { $_ -eq "'" }).Count
    return ($doubleQuotes % 2 -eq 0) -and ($singleQuotes % 2 -eq 0)
}

function Format-CommentReminder {
    param([string] $FileName, $Blocks)

    $lines = @("Comments added to $FileName by this edit:")
    foreach ($block in ($Blocks | Select-Object -First $MaxBlocksShown)) {
        $lines += '  ' + (Format-CommentBlock -Block $block)
    }
    if ($Blocks.Count -gt $MaxBlocksShown) {
        $lines += "  +$($Blocks.Count - $MaxBlocksShown) more"
    }
    $lines += 'Invoke the d:comments skill and judge each one against it. Delete each one that does not pass.'
    return $lines -join "`n"
}

function Format-CommentBlock {
    param($Block)

    $size = if ($Block.LineCount -eq 1) { '1 line' } else { "$($Block.LineCount) lines" }
    $preview = $Block.FirstLine
    if ($preview.Length -gt $MaxPreviewLength) {
        $preview = $preview.Substring(0, $MaxPreviewLength) + ' ...'
    }
    if ($null -eq $Block.LineNumber) {
        return "($size): $preview"
    }
    return "L$($Block.LineNumber) ($size): $preview"
}

if ($MyInvocation.InvocationName -ne '.') {
    try {
        $ErrorActionPreference = 'Stop'
        Main
    }
    catch {
        # A reminder is optional. A failure here must never break the Write or Edit.
    }
    exit 0
}
